### ISSUE TITLE
Import Arduino.h

### ISSUE THREAD

**Issue by yerlaser** [ZigEmbeddedGroup/espressif-esp#12]
Since Ziglang is so good at importing C libs, wouldn't it be easier to start with simply importing `Arduino.h` from Arduino project with ESP32 board installed.

**Comment by MasterQ32** [comment]
Arduino is not using C, but C++, so we can't use the Arduino libs from C++. Also the code quality of the Arduino project is not up to our standards

**Comment by yerlaser** [comment]
OK. Thanks for the answer!
