### ISSUE TITLE
ESP32 setup

### ISSUE THREAD

**Issue by kanstantsin-bucha** [ZigEmbeddedGroup/espressif-esp#21]
Hi! 

Thank you for your work in bringing the zig lang to the ESP.

How to flash result binary? Is it elf or binary? Is it full flash (offset 0x00) or just executable (0x1000)?

Is there a way to compile the binaries for the ESP32 chip?

If there are simple steps to do so, please point me to the documentation I should read.

Best,

**Comment by MasterQ32** [comment]
We can currently only support ESP32-C3, no Xtensa based ESP32 is supported
